//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Web.Ground.RateItWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectId", Namespace="http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    [System.SerializableAttribute()]
    public partial struct ObjectId : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _incrementField;
        
        private int _machineField;
        
        private short _pidField;
        
        private int _timestampField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _increment {
            get {
                return this._incrementField;
            }
            set {
                if ((this._incrementField.Equals(value) != true)) {
                    this._incrementField = value;
                    this.RaisePropertyChanged("_increment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _machine {
            get {
                return this._machineField;
            }
            set {
                if ((this._machineField.Equals(value) != true)) {
                    this._machineField = value;
                    this.RaisePropertyChanged("_machine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short _pid {
            get {
                return this._pidField;
            }
            set {
                if ((this._pidField.Equals(value) != true)) {
                    this._pidField = value;
                    this.RaisePropertyChanged("_pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _timestamp {
            get {
                return this._timestampField;
            }
            set {
                if ((this._timestampField.Equals(value) != true)) {
                    this._timestampField = value;
                    this.RaisePropertyChanged("_timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RateItWebService.IRateItController")]
    public interface IRateItController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/UserRegister", ReplyAction="http://tempuri.org/IRateItController/UserRegisterResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RateIt.Common.Core.QueryResults.UserLoginQueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RateIt.Common.Core.QueryResults.StoreListQueryResult))]
        RateIt.Common.Core.QueryResults.BaseQueryResult UserRegister(RateIt.Common.Core.Entities.Users.User registrationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/UserRegister", ReplyAction="http://tempuri.org/IRateItController/UserRegisterResponse")]
        System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.BaseQueryResult> UserRegisterAsync(RateIt.Common.Core.Entities.Users.User registrationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/UserLogin", ReplyAction="http://tempuri.org/IRateItController/UserLoginResponse")]
        RateIt.Common.Core.QueryResults.UserLoginQueryResult UserLogin(RateIt.Common.Core.Entities.Users.UserLoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/UserLogin", ReplyAction="http://tempuri.org/IRateItController/UserLoginResponse")]
        System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.UserLoginQueryResult> UserLoginAsync(RateIt.Common.Core.Entities.Users.UserLoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/UserLogout", ReplyAction="http://tempuri.org/IRateItController/UserLogoutResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RateIt.Common.Core.QueryResults.UserLoginQueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RateIt.Common.Core.QueryResults.StoreListQueryResult))]
        RateIt.Common.Core.QueryResults.BaseQueryResult UserLogout(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/UserLogout", ReplyAction="http://tempuri.org/IRateItController/UserLogoutResponse")]
        System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.BaseQueryResult> UserLogoutAsync(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/StoreRegister", ReplyAction="http://tempuri.org/IRateItController/StoreRegisterResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RateIt.Common.Core.QueryResults.UserLoginQueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RateIt.Common.Core.QueryResults.StoreListQueryResult))]
        RateIt.Common.Core.QueryResults.BaseQueryResult StoreRegister(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo, RateIt.Common.Core.Entities.Stores.Store registrationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/StoreRegister", ReplyAction="http://tempuri.org/IRateItController/StoreRegisterResponse")]
        System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.BaseQueryResult> StoreRegisterAsync(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo, RateIt.Common.Core.Entities.Stores.Store registrationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/GetStoresAtLocation", ReplyAction="http://tempuri.org/IRateItController/GetStoresAtLocationResponse")]
        RateIt.Common.Core.QueryResults.StoreListQueryResult GetStoresAtLocation(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo, RateIt.Common.Classes.GeoPoint location, RateIt.Common.Core.Constants.StoreQueryAreaLevel areaLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateItController/GetStoresAtLocation", ReplyAction="http://tempuri.org/IRateItController/GetStoresAtLocationResponse")]
        System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.StoreListQueryResult> GetStoresAtLocationAsync(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo, RateIt.Common.Classes.GeoPoint location, RateIt.Common.Core.Constants.StoreQueryAreaLevel areaLevel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRateItControllerChannel : RateIt.Web.Ground.RateItWebService.IRateItController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RateItControllerClient : System.ServiceModel.ClientBase<RateIt.Web.Ground.RateItWebService.IRateItController>, RateIt.Web.Ground.RateItWebService.IRateItController {
        
        public RateItControllerClient() {
        }
        
        public RateItControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RateItControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateItControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateItControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RateIt.Common.Core.QueryResults.BaseQueryResult UserRegister(RateIt.Common.Core.Entities.Users.User registrationInfo) {
            return base.Channel.UserRegister(registrationInfo);
        }
        
        public System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.BaseQueryResult> UserRegisterAsync(RateIt.Common.Core.Entities.Users.User registrationInfo) {
            return base.Channel.UserRegisterAsync(registrationInfo);
        }
        
        public RateIt.Common.Core.QueryResults.UserLoginQueryResult UserLogin(RateIt.Common.Core.Entities.Users.UserLoginInfo loginInfo) {
            return base.Channel.UserLogin(loginInfo);
        }
        
        public System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.UserLoginQueryResult> UserLoginAsync(RateIt.Common.Core.Entities.Users.UserLoginInfo loginInfo) {
            return base.Channel.UserLoginAsync(loginInfo);
        }
        
        public RateIt.Common.Core.QueryResults.BaseQueryResult UserLogout(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo) {
            return base.Channel.UserLogout(sessionInfo);
        }
        
        public System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.BaseQueryResult> UserLogoutAsync(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo) {
            return base.Channel.UserLogoutAsync(sessionInfo);
        }
        
        public RateIt.Common.Core.QueryResults.BaseQueryResult StoreRegister(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo, RateIt.Common.Core.Entities.Stores.Store registrationInfo) {
            return base.Channel.StoreRegister(sessionInfo, registrationInfo);
        }
        
        public System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.BaseQueryResult> StoreRegisterAsync(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo, RateIt.Common.Core.Entities.Stores.Store registrationInfo) {
            return base.Channel.StoreRegisterAsync(sessionInfo, registrationInfo);
        }
        
        public RateIt.Common.Core.QueryResults.StoreListQueryResult GetStoresAtLocation(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo, RateIt.Common.Classes.GeoPoint location, RateIt.Common.Core.Constants.StoreQueryAreaLevel areaLevel) {
            return base.Channel.GetStoresAtLocation(sessionInfo, location, areaLevel);
        }
        
        public System.Threading.Tasks.Task<RateIt.Common.Core.QueryResults.StoreListQueryResult> GetStoresAtLocationAsync(RateIt.Common.Core.Entities.Session.SessionInfo sessionInfo, RateIt.Common.Classes.GeoPoint location, RateIt.Common.Core.Constants.StoreQueryAreaLevel areaLevel) {
            return base.Channel.GetStoresAtLocationAsync(sessionInfo, location, areaLevel);
        }
    }
}
